### ISSUE TITLE
Searching Events in icingaweb2 search only in one index

### ISSUE THREAD

**Issue by winter1967** [lazyfrosch/icingaweb2-logstash#1]
We have some more indexes than logstash-_, for example winlogbeat-_.

When i search in the module, the search uses only the logstash index.

 grep -R logstash- ./
./application/views/scripts/error-config.phtml:    index_pattern = logstash-*
./application/clicommands/CheckCommand.php:        $this->index_pattern = $this->Config()->get('elasticsearch', 'index_pattern', 'logstash-_');
./library/Logstash/Controller.php:        $this->index_pattern = $this->Config()->get('elasticsearch', 'index_pattern', 'logstash-_');
./CONCEPT.md:    vars.logstash_index = "logstash-*"

Where to change the index? I don't know.. Changing the CheckCommand.php in
get('elasticsearch', 'index_pattern', '*');
have no sucess...

**Comment by lazyfrosch** [comment]
Hey Mr. winter ;)
You can change the index in the ini file.

Usually `/etc/icingaweb2/modules/logstash/config.ini`, there you can add:

```
index_pattern = "logstash-*,winlogbeat-*"
```

There is only a global setting.

**Comment by winter1967** [comment]
Thank you, it works ☺

Von: Markus Frosch [mailto:notifications@github.com]
Gesendet: Freitag, 30. September 2016 15:56
An: lazyfrosch/icingaweb2-logstash
Cc: Winter, Wolfgang; Author
Betreff: Re: [lazyfrosch/icingaweb2-logstash] Searching Events in icingaweb2 search only in one index (#1)

Closed #1https://github.com/lazyfrosch/icingaweb2-logstash/issues/1.
